### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by rekmolly** [daniellockyer/apkdiff#4]
python apkdiff.py -o test xxx.apk xxx2.apk I get next error:

`Traceback (most recent call last):
  File "apkdiff.py", line 145, in <module>
    main()
  File "apkdiff.py", line 64, in main
    apktoolit(args.apk1, at1)
  File "apkdiff.py", line 81, in apktoolit
    call(["apktool", "d", "--no-debug-info", "-o", dir, file], stdout=open(os.devnull, 'w'), stderr=STDOUT)
  File "\Programs\Python\Python38-32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

What is the reason for this?

**Comment by xurixin** [comment]
Traceback (most recent call last):
  File "apkdiff.py", line 145, in <module>
    main()
  File "apkdiff.py", line 64, in main
    apktoolit(args.apk1, at1)
  File "apkdiff.py", line 81, in apktoolit
    call(["apktool", "d", "--no-debug-info", "-o", dir, file], stdout=open(os.devnull, 'w'), stderr=STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Kladdkaka** [comment]
if you install apktool using https://github.com/lukesampson/scoop/, then you can change the string "apktool" to "apktool.cmd" here https://github.com/daniellockyer/apkdiff/blob/5c55afb3fd450e55223686d2064bafab82cdacb2/apkdiff.py#L81

And it will work :)

**Comment by umkhanqta** [comment]
I am using ubuntu and still getting same error
i have put 
apktool_2.4.0.jar
in the same directory where apkdiff.py is present

**Comment by umkhanqta** [comment]
getting error 

Traceback (most recent call last):
  File "apkdiff.py", line 146, in <module>
    main()
  File "apkdiff.py", line 67, in main
    compare(at1, at2)
  File "apkdiff.py", line 87, in compare
    report_full_closure(compared)
  File "apkdiff.py", line 91, in report_full_closure
    print(list(self.diff_files))
  File "/usr/lib/python2.7/filecmp.py", line 238, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python2.7/filecmp.py", line 174, in phase3
    xx = cmpfiles(self.left, self.right, self.common_files)
  File "/usr/lib/python2.7/filecmp.py", line 238, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python2.7/filecmp.py", line 143, in phase2
    for x in self.common:
  File "/usr/lib/python2.7/filecmp.py", line 238, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python2.7/filecmp.py", line 132, in phase1
    a = dict(izip(imap(os.path.normcase, self.left_list), self.left_list))
  File "/usr/lib/python2.7/filecmp.py", line 238, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python2.7/filecmp.py", line 124, in phase0
    self.left_list = _filter(os.listdir(self.left),
OSError: [Errno 2] No such file or directory: './myoutput/1/at/'

**Comment by umkhanqta** [comment]
> if you install apktool using https://github.com/lukesampson/scoop/, then you can change the string "apktool" to "apktool.cmd" here
> 
> https://github.com/daniellockyer/apkdiff/blob/5c55afb3fd450e55223686d2064bafab82cdacb2/apkdiff.py#L81
> 
> And it will work :)

need to change
call(["apktool", "d", "--no-debug-info", "-o", dir, file], stdout=open(os.devnull, 'w'), stderr=STDOUT, shell=True) 
for ubuntu
