### ISSUE TITLE
FileNotFoundError Exception on report_full_closure

### ISSUE THREAD

**Issue by enovella** [daniellockyer/apkdiff#8]
```sh
[18:16 edu@xps apkdiff]  (master)>  python3 apkdiff.py ~/Downloads/Slack_v21.10.10.0_apkpure.com.apk ~/Downloads/Slack_v22.02.10.0_apkpure.com.apk 

			 apktool

Extracted 'classes.dex' from '/home/edu/Downloads/Slack_v21.10.10.0_apkpure.com.apk'.
Extracted 'classes.dex' from '/home/edu/Downloads/Slack_v22.02.10.0_apkpure.com.apk'.
Running apktool against '/home/edu/Downloads/Slack_v21.10.10.0_apkpure.com.apk'
[OK]
Running apktool against '/home/edu/Downloads/Slack_v22.02.10.0_apkpure.com.apk'
[OK]

Traceback (most recent call last):
  File "apkdiff.py", line 145, in <module>
    main()
  File "apkdiff.py", line 67, in main
    compare(at1, at2)
  File "apkdiff.py", line 87, in compare
    report_full_closure(compared)
  File "apkdiff.py", line 91, in report_full_closure
    for name in self.diff_files:
  File "/usr/lib/python3.6/filecmp.py", line 247, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python3.6/filecmp.py", line 183, in phase3
    xx = cmpfiles(self.left, self.right, self.common_files)
  File "/usr/lib/python3.6/filecmp.py", line 247, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python3.6/filecmp.py", line 152, in phase2
    for x in self.common:
  File "/usr/lib/python3.6/filecmp.py", line 247, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python3.6/filecmp.py", line 141, in phase1
    a = dict(zip(map(os.path.normcase, self.left_list), self.left_list))
  File "/usr/lib/python3.6/filecmp.py", line 247, in __getattr__
    self.methodmap[attr](self)
  File "/usr/lib/python3.6/filecmp.py", line 133, in phase0
    self.left_list = _filter(os.listdir(self.left),
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/apkdiff/1/at/'
```

**Comment by daniellockyer** [comment]
I believe this should be fixed with https://github.com/daniellockyer/apkdiff/pull/9
